# Generated by Django 4.2.30 on 2026-04-26 15:30

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Phase',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('order', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Roadmap',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('goal', models.CharField(max_length=500)),
                ('why', models.TextField(blank=True)),
                ('time_per_week', models.CharField(blank=True, max_length=50)),
                ('budget', models.CharField(blank=True, max_length=50)),
                ('skill_level', models.CharField(blank=True, max_length=50)),
                ('support_obstacles', models.TextField(blank=True)),
                ('life_commitments', models.TextField(blank=True)),
                ('biggest_obstacle', models.TextField(blank=True)),
                ('past_experience', models.TextField(blank=True)),
                ('success_3_months', models.TextField(blank=True)),
                ('success_1_year', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('why', models.TextField(blank=True)),
                ('estimated_time', models.CharField(blank=True, max_length=100)),
                ('tag', models.CharField(choices=[('skill', 'Skill'), ('habit', 'Habit'), ('resource', 'Resource'), ('social', 'Social'), ('mindset', 'Mindset')], default='skill', max_length=20)),
                ('status', models.CharField(choices=[('todo', 'To Do'), ('in_progress', 'In Progress'), ('done', 'Done')], default='todo', max_length=20)),
                ('blocker_note', models.TextField(blank=True)),
                ('order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('phase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='api.phase')),
            ],
        ),
        migrations.AddField(
            model_name='phase',
            name='roadmap',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phases', to='api.roadmap'),
        ),
    ]
